// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


int valorecg;
int valoremg;
int valoroximetria_ir;
int valoroximetria_r;

void initProperties(){

  ArduinoCloud.addProperty(valorecg, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(valoremg, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(valoroximetria_ir, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(valoroximetria_r, READ, ON_CHANGE, NULL);

}

////////////////////////////ATTENTION!!!////////////////////////////////
// ATTENTION: No device is currently associated to this Thing,        //
// hence the Connection Handler code could not be generated           //
// Please associate an existing or new device or manually create your //
// instance of Connection Handler                                     //
// Eg.                                                                // 
// WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);   //
////////////////////////////////////////////////////////////////////////

#error "No device is currently associated to this Thing, hence the Connection Handler code could not be generated"
